= Welcome to {lab_name}!

[%hardbreaks]

== はじめに

今日のダイナミックなIT環境において、組織はクラウドネイティブ・イノベーションの要求と並行して、従来の仮想化管理の複雑さに取り組んでいます。このワークショップでは、Red Hat OpenShift VirtualizationをAnsible Automation PlatformおよびRed Hat Advanced Cluster Management for Kubernetesと組み合わせることで、仮想ベースかコンテナベースかを問わず、あらゆるワークロードに対応する統合型、効率的、かつ安全なプラットフォームを実現する方法を示し、ITプロフェッショナルが自信を持ってこのハイブリッドな現実に対応できるよう支援します。

このラボは、大変好評を博した https://www.redhat.com/en/events/na-red-hat-openshift-virtualization[Experience OpenShift Virtualization Roadshow^] ラボの続編であり、環境を管理し、導入2日目以降に仮想マシン管理者に求められる重要な運用タスクを実行するための知識とツールを提供します。これにより、仮想化されたワークロードは、初期導入後も長期間にわたって効率的に管理・保守されます。

== ラボのストーリー

あなたは「Legacy Systems Inc.」のリードプラットフォームエンジニア、またはVM管理者だと想像してください。同社は従来型の仮想化ワークロードを基盤としていますが、急速に変化する市場の需要に対応し、モダナイズする必要性が高まっています。CIOは最近、戦略の転換を指示しました。運用の複雑さを軽減し、俊敏性を向上させ、コンプライアンスを確保するため、すべての仮想化ワークロードとコンテナ化ワークロードを統合プラットフォームに統合するというものです。この指示は、仮想化ベンダー市場における最近の市場の変化が一因となり、既存の投資と戦略の見直しが求められています。
VMを移行し、一貫性のあるアプリケーションプラットフォーム上でワークロードを統合できるという理由から、Red Hat OpenShiftとRed Hat OpenShift Virtualizationを戦略的プラットフォームとして選択しました。今、チームはこの新しい環境におけるDay 2運用を習得するという重要な課題に直面しています。

== 含まれる Red Hat 製品

*OpenShift Virtualization* を使用すると、Kubernetes ベースの最新インフラストラクチャに仮想マシンを導入できます。新規アプリケーションの開発と配信、既存アプリケーションのモダナイゼーションが可能になり、仮想マシン、コンテナ、サーバーレス機能で構成されるアプリケーションを作成できます。これらはすべて、Kubernetes ネイティブのツールとパラダイムを使用して一括管理されます。

*Ansible Automation Platform* を使用すると、プラットフォームエンジニアリングチームと DevOps チームは、物理、クラウド、仮想、エッジ環境全体にわたって自動化を構築、管理、拡張できます。Ansible Automation Platform を使用すると、インフラストラクチャ、ネットワークコンポーネント、アプリケーション、ストレージ、セキュリティ、ITSM などを網羅する自動化ワークフローによって、一貫性とコンプライアンスを確保できます。

*Red Hat Advanced Cluster Managment for Kubernetes* は、運用ポリシーが組み込まれた単一のコンソールから、クラスター全体のエンドツーエンドの管理、可視性、制御を提供します。データセンター、クラウド、エッジ環境にデプロイされたアプリケーションのデプロイ、複数のクラスタの管理、複数のクラスタ全体へのポリシー適用を行うことで、Red Hat OpenShift® の価値をさらに高めます。


== このラボへの参加で最もメリットを得られるのは誰ですか？

このワークショップは、仮想化戦略の最適化、運用の効率化、そして将来のアプリケーションモダナイゼーションへの準備を目指す仮想マシン管理者、仮想インフラストラクチャ管理者、プラットフォームエンジニア、そしてIT運用チームを対象としています。

== このラボで扱う内容

このラボは、*5つの* 主要セクションで構成されています。

* _パフォーマンス、スケーラビリティ、トラブルシューティング_：このセクションでは、Red Hat OpenShift クラスターのパフォーマンスメトリックをいくつか確認し、高負荷シナリオをシミュレートします。そして、Red Hat OpenShift と OpenShift Virtualization で利用可能なツールとリソースを活用してリソースを適切にスケーリングし、問題のトラブルシューティングと軽減を行う方法を検討します。

* _セキュリティとコンプライアンス_：このセクションでは、Red Hat OpenShift Compliance Operator を使用して、クラスター・インフラストラクチャが社内のセキュリティ基準を満たしていることを確認します。また、Red Hat OpenShift に統合された RBAC 制御を使用して追加のユーザーアカウントを作成し、クラスター内で各アカウントに特定の管理権限を割り当てることで、社内の役割と義務の分離を支援する方法についても紹介します。

* _高度なネットワークとセキュリティ_：このセクションでは、Network Observability Operator を使用してネットワーク使用率を調査し、トラフィックフローのカスタムグラフを作成します。次に、クラスター内外、そして内部のプロジェクト間のネットワークトラフィックを制御および保護するための、具体的なネットワークポリシーを作成できることを示します。

* _仮想マシンの自動化_：このセクションでは、管理者が環境内で日常的に実行することが期待されるさまざまな管理タスクを取り上げ、これらのタスクの多くがAnsible Automation Platformで簡単に自動化できることを説明します。

* _仮想ワークロードの高度な管理_：このセクションでは、Red Hat Advanced Cluster Managment for Kubernetesを紹介します。これにより、中央のハブクラスターから単一のインターフェースを介して、多数のRed Hat OpenShiftクラスターを検出および管理できます。RHACMを使用すると、コンテナベースでも仮想マシンベースでも、これらのリモートクラスターとそのワークロードを監視および管理できます。

== ラボ環境の要件

* 参加者は、Webブラウザとインターネット接続を備えたパソコンをご持参ください。
* Firefoxでは一部のコピー/ペースト機能が現時点では動作しないため、Chromiumベースのブラウザを推奨します。
* リモートアクセスコンソールはデフォルトでUSキーボードレイアウトを使用するため、他の国のキーボードレイアウトで特殊文字がどこに配置されているかを把握しておくか、サポートされているブラウザでコピー/ペースト機能を使用することをお勧めします。

=== OpenShift コンソールおよび Ansible Automation Platform の認証情報

OpenShift クラスターコンソールは {openshift_cluster_console_url}[こちら^] からご利用いただけます。

ログインには以下の方法があります。

* *User:* {openshift_cluster_admin_username}
* *Password:* {openshift_cluster_admin_password}

Ansible Automation Platform コンソールは {aap_controller_web_url}[ここ^] からご利用いただけます。

* *User:* {aap_controller_admin_user}
* *Password* {aap_controller_admin_password}

=== Version Information

このラボは、以下のソフトウェアバージョンを使用して開発されています。

* Red Hat OpenShift 4.18.23
* Red Hat OpenShift Virtualization 4.18.13
* Red Hat Ansible Automation Platform 2.5
* Red Hat Advanced Cluster Management for Kubernetes 2.14.0

(2025年9月18日時点の情報です)
